name: test-and-lint
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - unstable
      - web-ui-support
  pull_request:
permissions:
  contents: read
jobs:
  gotest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - name: go-generate
        run: go generate ./...
      - name: go-test
        run: |
          go test ./pkg/...

  golangci-linux:
    name: golangci-lint
    runs-on: ubuntu-latest
    env:
      GOOS: linux
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - name: go-generate
        run: GOOS=linux go generate ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.2
